import type { Metadata } from "next";
import { Geist, Geist_Mono, Lexend } from "next/font/google";
import "./globals.css";
import ConfirmProvider from "../context/ConfirmProvider";
import BackToTop from "../components/shared/BackToTop";
import { Toaster } from "react-hot-toast";
import { CartProvider } from "../context/CartProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lexend = Lexend({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`  ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`${lexend.className} min-h-full flex flex-col`}>
        <Toaster position="top-center" />
        <ConfirmProvider>
          <CartProvider>
          {children}
          <BackToTop />
          </CartProvider>
        </ConfirmProvider>
      </body>
    </html>
  );
}
